### ISSUE TITLE
Findbugs annotations should have optional or provided dependency

### ISSUE THREAD

**Issue by marschall** [google/flogger#31]
Currently both `flogger` and `flogger-system-backend` have a default (`compile`) dependency on `com.google.code.findbugs:jsr305` which means it is packaged with every application. It this not required as Findbugs annotations are not required to run flogger. A better solution would be to either declare the dependency as `optional` or change the scope to `provided`.

**Comment by jbduncan** [comment]
This seems related to https://github.com/google/guava/issues/2824 and https://github.com/google/guava/issues/2721 to me. So my personal gut reaction is to keep the JSR305 annotations as a `compile` dependency.

**Comment by marschall** [comment]
It is similar.

**Comment by marschall** [comment]
It's not causing any issues. It just causing additional work for users who don't want to deploy it as they have to exclude it or live with the footprint of the JAR in their deployment.

**Comment by hagbard** [comment]
I think jsr305 is a tiny jar in terms of bytes, but I see your point. I'll watch out to see if Guava do anything about this and follow suit if they do. I think if people are really worried about JAR size for deployment they would be using Proguard or similar to strip dead code, so it doesn't feel like it should be a big deal to me.

I'm closing this since there's nothing I plan to do right now about it, but rest assured I've not forgotten. I've added myself to the Guava bug tracking the same thing.
