### ISSUE TITLE
Add extension to log() for inline return-statement

### ISSUE THREAD

**Issue by brainbytes42** [google/flogger#42]
Coming from SLF4J/Logback, I am now lokking into flogger and log4j2 for future work...

While log4j2 is quite bulky and I like flogger's modern design, I was wondering if you'd be interested in an extension to log which returns the logged value? In log4j2, ther is a method called traceExit(T):T which does exactly that. For flogger I'd imagine something like `returning(T):T` which just calls log(T) and returns T, maybe with an optional text but not too much stuff. ;-)

    return log4j2.traceExit("foo");

> Exit with(foo)

Additionally, log4j provides the tracing of an entry-message to have a handle for the tracing of exit to be clear of input -> output... also a nice idea...

    EntryMessage entryMessage = log4j2.traceEntry("entry-msg {}", "some-param");
    // ...
    return log4j2.traceExit(entryMessage, "result"); 

> Enter entry-msg some-param
...
> Exit entry-msg some-param: result

What Du you think about that? Would that fit into flogger? For example like that:

    <T> T returning(T val){
        log("Returning: %s", val);
        return val;
    }

    <T> T returning(T val, String message){
        log("Returning [%s]: %s", message, val);
        return val;
    }

**Comment by hagbard** [comment]
Hmm, I'm not sure. There's all sorts of questions in my head around "who defines the level for this log?" and "what if it's disabled?" and what if the paired "exit" method just isn't called (it'll look like you logged, but then nothing appears).

This is a bit similar to logging with "Futures", which we ultimately decided against. I quite liked the idea of being able to say:
  logger.atSevere().ifFailed(someFuture).log("Error message");
but there were lots of hurdles and we decided it was just too confusing as an API.

Habitual entry/exit logging is something we don't do everywhere in Google code, so it's not a use case I've got a good feel for, so if you know of open-source code/docs which discuss it as a pattern, that would help me get more of a feel for it.

**Comment by brainbytes42** [comment]
Thanks for coming back to this.

First, the level comes for free, thanks to the fluent architecture: It's just `return flogger.atFine().logReturning(theValue);` -- so the level is defined the same way as for any other logger.

The other question you mentioned is far more critical for my suggestion: Even if the level is disabled and a NoOp-Api is returned, the given value has to be returned. 
But a short look into the code gave me a little relief: The NoOp.log() is just an empty method, so using the proposed implementation, the call to log would just return immediately and the value would be returned. Only downside: As the API is an interface and has no common baseclass, the new method would have to be implemented both in LogContext and NoOp... Default-Methods in interfaces could become handy, but iirc the Java-Version wasn't 8 at least? Or do I miss something?

An alternative would be to put it into AbstractLogger kind of as an abbreviation for a standard-toolchain... downside: little violation of fluent api concept and fixed level. upside: way shorter and one single place... it's kind a meta-method, as it calls into the api... so maybe that wouldn't be too bad?

Entry/Exit-logging wasn't anything I was doing regularly, too - maybe because it's a little verbose to have two lines off logging in each method... but with inlining it, we would have one line less, so I think for more important methods that would come in very handy...  As I said, I found it at log4j v2 -- they have a nice introduction here, also mentioning logging of exception-catching: [log4j](https://logging.apache.org/log4j/2.x/manual/flowtracing.html).

Final thought, reading the above documentation of log4j again in the context of our discussion:
They mention som kind of marker to be able to filter the flowtrace. That would advocate the implementation inside the API, becaus then it would be possible to add metadata inside the LogContext, which finally could be read by the Backend, for example for printing, filtering or for a log4j backend to set their marker.

**Comment by hagbard** [comment]
I'm not disputing if we can do something like this with Flogger's API (I don't have an opinion on that yet because I'm not sure exactly what's being suggested). I'm more interested in if we should do anything at all.

To convince me of the need to add a new API, you'd need to demonstrate how useful it is (e.g. stats for how many people use it in the real world). What does representative code look like using this mechanism, and would would it be if this mechanism didn't exist. It's too soon to discuss how it would be implemented.

There are lots of features in logging APIs Flogger has explicitly chosen not to implement (Flogger is replacing many private logging APIs inside Google) and we always look at what's being done by those loggers (and how valuable it is in real code) before deciding whether to support it or not. In most cases it turns out that these features don't really "carry their weight" in the API (every new method in the API is a burden for maintenance and more complexity for users to understand).

Since almost no projects in Google use entry/exit tracing (*) that hints to me that maybe it's not a really valuable/necessary feature for a logging API (if it was used a lot, it would have been added already). But Google has some quirky code patterns, so maybe in the "real world" it's more valued - I just don't know (yet).

(*) The JDK logger has a similar entering/exiting method pair which in all of Google's Java code are called about 200 times. This is many orders of magnitude less than things like info/warning log statements. But perhaps if there was a better, simpler way to do this that number would grow...

On a side note, entry/exit logging is about the best use case for Aspect Oriented Programming I know, since it solves this sort of thing pretty seamlessly (but comes with a bunch of other costs).

**Comment by brainbytes42** [comment]
Thanks for your valid explanation. Unfortunately, I don't have any numbers from real world code or have any idea, where I could find them... I tried searching github, but that wasn't successful. ;-)
